oem-ibm: FRU: Add UTIL entry
ibm-openbmc/pldm pull request #350
Opened 2023-01-29 07:40 UTC by lxwinspur

Add UTIL that has RT,F5,F6 entry to existing FRU configuration. Resolves: https://github.com/ibm-openbmc/dev/issues/3616

Tested: use pldmtool GetFRURecordTableMetadata cmd to verify the output.

Signed-off-by: George Liu <liuxiwei@inspur.com>

2023-01-29 07:42 UTC, lxwinspur commented
@jaypadath @mzipse 
Please take a look at this PR, thanks

2023-02-06 10:32 UTC, manojkiraneda approved these changes

2023-02-06 10:57 UTC, jaypadath approved these changes

2023-02-17 06:22 UTC, lxwinspur commented
Updated fru_field_type for F5 and F6
F5 -> 18
F6 -> 19

2023-02-24 10:12 UTC, jaypadath requested changes

2023-02-24 10:12 UTC, jaypadath commented on oem/ibm/configurations/fru/Motherboard_UTIL.json
> +            "fru_field_type": 18,
Please update it as 3 instead of 18

2023-02-24 10:12 UTC, jaypadath commented on oem/ibm/configurations/fru/Motherboard_UTIL.json
> +            "fru_field_type": 19,
Please update it as 4 instead of 19

2023-02-27 07:22 UTC, jaypadath approved these changes
Please ignore my previous comment and the values 18 and 19 are good. Approving the same.

2025-04-29 10:33 UTC, manojkiraneda commented
This is no longer needed, the code is already merged in a different PR.

2025-04-29 10:33 UTC, closed without merging