PLDM: Implementing Phosphor-Logging/LG2 logging
ibm-openbmc/pldm pull request #364
Opened 2023-02-16 13:45 UTC by riyadixitagra

This commit adds changes in PLDM for implementing
structured LG2 logging, thereby moving away from
std::cout/cerr practice of logging which are
output streams and not logging mechanism.

PLDM now can make use of lg2 features like accurate CODE LINE Number and CODE_FUNCTION Name and better detailing in json object values which can be used in log tracking.

Tested:
Ran a power off, on, cycle, and reset-reload.

2023-02-20 15:44 UTC, geissonator commented
add to approvelist

2023-03-09 05:55 UTC, Pavithrab7 requested changes

2023-03-09 05:55 UTC, Pavithrab7 commented on common/utils.cpp
> +        lg2::error(" Failed to obtain a record. ERROR = {KEY0}","KEY0", e.what());
make lg2::error as error (remove lg2)

2023-03-09 05:55 UTC, Pavithrab7 commented on fw-update/device_updater.cpp
> +        lg2::error("Component apply complete, EID = {KEY0}, COMPONENT_VERSION = {KEY1}", "KEY0", unsigned(eid), "KEY1", compVersion);
info log

2023-03-09 05:55 UTC, Pavithrab7 commented on fw-update/device_updater.cpp
> +        lg2::error("Component verification complete, EID={KEY0}, COMPONENT_VERSION={KEY1}", "KEY0", unsigned(eid), "KEY1", compVersion);
info log

2023-03-09 05:55 UTC, Pavithrab7 commented on fw-update/device_updater.cpp
> +        lg2::error("Component Transfer complete, EID = {KEY0}, COMPONENT_VERSION = {KEY1}", "KEY0", unsigned(eid), "KEY1", compVersion);
info log

2023-03-09 05:55 UTC, Pavithrab7 commented on host-bmc/dbus/deserialize.cpp
> +        lg2::error("Restoring dbus of type : {KEY0}", "KEY0", type);
generally std::cout can be made a info log rather than error log

2023-03-09 05:55 UTC, Pavithrab7 commented on host-bmc/host_pdr_handler.cpp
> +            lg2::error("Host is UP & Completed the PDR Exchange with host");
same as above

2023-03-09 05:55 UTC, Pavithrab7 commented on host-bmc/host_pdr_handler.cpp
> +        lg2::error( "Getting the response. PLDM RC = {KEY0}", "KEY0", lg2::hex, (uint16_t)response->payload[0]);
same as above, please check all the std::cout traces and make it info rather than error

2023-03-09 05:55 UTC, Pavithrab7 commented on common/utils.cpp
> +        lg2::error(" Failed to obtain a record. ERROR = {KEY0}","KEY0", e.what());
+1

2023-05-23 05:32 UTC, closed without merging