oem-ibm: Adding BIOS attribute for dynamic deallocation of Memory
ibm-openbmc/pldm pull request #539
Opened 2024-05-28 09:55 UTC by riyadixitagra

This commit adds a BIOS attribute for allowing user to enable/disable the dynamic deallocation of memory.

Tested: Verified the BIOS attribute with get bios attribute command from pldmtool.

2024-05-29 03:31 UTC, ArchanaKakani reviewed
Do we need to add one more bios attribute `hb_predictive_mem_guard_current` as changes to `hb_predictive_mem_guard` bios attribute takes effect after next reboot?

2024-06-03 06:42 UTC, Pavithrab7 requested changes
We need a _current attribute too, please check with the HB team and update.

2024-06-07 09:13 UTC, Pavithrab7 approved these changes

2024-06-07 09:13 UTC, Pavithrab7 commented
can you add a comment about what is dynamic memory allocation in the commit message?

2024-06-24 02:31 UTC, closed without merging