oem-ibm: Capacity on demand licensing support
ibm-openbmc/pldm pull request #551
Opened 2024-06-10 08:52 UTC by jaypadath

This commit supports:

1. Creation or update of new license interfaces and properties supplied by host
2. Clearing of license status to Unknown, during host power off transition
3. Restoration of license interfaces during reset reload and setting the license status to Unknown

Tested By:

1. Verified that dbus hosting is done by pldm
2. CoD(Capacity on demand) values are coming up in the BMC
3. Verified that reboot of BMC does not clear values

Change-Id: I9377e66753c2df7f8e1ac8b6a4ed285db69ad090

2024-06-10 09:17 UTC, Pavithrab7 approved these changes
@jaypadath Changes looks good. But let us get the enum values `pldm_license_install_status` from PDI in a seperate PR.

2024-06-10 09:17 UTC, Pavithrab7 commented on oem/ibm/libpldmresponder/file_io_type_lic.cpp
> +    if (buffer != nullptr)
if(!buffer)

2024-06-10 09:24 UTC, jaypadath commented
> @jaypadath Changes looks good. But let us get the enum values `pldm_license_install_status` from PDI in a seperate PR.

Okay will take care of that separately

2024-06-10 09:38 UTC, Pavithrab7 requested changes

2024-06-10 09:38 UTC, Pavithrab7 commented on oem/ibm/libpldmresponder/file_io.hpp
> +    std::unique_ptr<sdbusplus::bus::match::match>
match_t

2024-06-10 10:14 UTC, jaypadath commented on host-bmc/custom_dbus.cpp
> +    if (operationalStatus.find(path) == operationalStatus.end())
Done

2024-06-10 10:15 UTC, jaypadath commented on host-bmc/custom_dbus.cpp
> +    if (operationalStatus.find(path) != operationalStatus.end())
Done

2024-06-10 10:15 UTC, jaypadath commented on host-bmc/custom_dbus.cpp
> +    if (codLic.find(path) == codLic.end())
Done

2024-06-10 10:15 UTC, jaypadath commented on host-bmc/custom_dbus.cpp
> +    if (availabilityState.find(path) == availabilityState.end())
Done

2024-06-10 10:15 UTC, jaypadath commented on host-bmc/custom_dbus.hpp
> +using LicIntf = sdbusplus::server::object::object<
Done

2024-06-10 10:15 UTC, jaypadath commented on host-bmc/custom_dbus.hpp
> +using AvailabilityIntf = sdbusplus::server::object::object<
Done

2024-06-10 10:15 UTC, jaypadath commented on host-bmc/custom_dbus.hpp
> +    sdbusplus::server::object::object<sdbusplus::xyz::openbmc_project::State::
Done

2024-06-10 10:15 UTC, jaypadath commented on oem/ibm/libpldmresponder/file_io.hpp
> +             handler](sdbusplus::message::message& msg) {
Done

2024-06-10 10:15 UTC, jaypadath commented on oem/ibm/libpldmresponder/file_io.hpp
> +    std::unique_ptr<sdbusplus::bus::match::match>
Done

2024-06-10 12:53 UTC, Pavithrab7 approved these changes

2024-06-10 16:01 UTC, rfrandse commented
jenkins run tests please

2024-06-10 16:36 UTC, jaypadath commented
jenkins run tests please

2024-06-11 03:54 UTC, Patel-Kamalkumar commented on common/utils.hpp
> -/** @struct CustomFD
this change is part of AIO commit, why it's showing here?

2024-06-11 03:55 UTC, Patel-Kamalkumar commented on oem/ibm/libpldmresponder/file_io.cpp
> -int DMA::transferHostDataToSocket(int fd, uint32_t length, uint64_t address)
this change is part of AIO commit, why it's showing here?

2024-06-11 04:01 UTC, Patel-Kamalkumar commented on host-bmc/custom_dbus.cpp
> +                                            path.c_str()));
c_str() not required here

2024-06-11 04:01 UTC, Patel-Kamalkumar commented on host-bmc/custom_dbus.cpp
> +                      pldm::utils::DBusHandler::getBus(), path.c_str()));
c_str() not required here

2024-06-12 15:24 UTC, closed without merging