softpoweroff: PLDM 1110 softoff rebase
ibm-openbmc/pldm pull request #554
Opened 2024-06-12 16:21 UTC by sagisin

2024-06-14 00:54 UTC, manojkiraneda requested changes
@sagisin Looks okay to me except that one minor comment.

2024-06-14 00:54 UTC, manojkiraneda commented on softoff/softoff.cpp
> +                          << rc << "\n";
this needs to change to lg2 ?

2024-06-14 08:49 UTC, sagisin commented on softoff/softoff.cpp
> +                          << rc << "\n";
done

2024-06-17 05:38 UTC, manojkiraneda approved these changes

2024-06-19 15:20 UTC, merged