oem-ibm: Introducing sensor design for SBE ocmb dump
ibm-openbmc/pldm pull request #594
Opened 2024-08-14 10:32 UTC by riyadixitagra

This commit introduces new oem sensor PDRs of state set id - PLDM_OEM_IBM_SBE_DUMP_UPDATE_STATE(32777) whose state will be set for ocmb dump progress status. This change implements the new sensor based dump design only for ocmb sbe dumps whereas the sbe PROC dump design remains unchanged. As part of this change PLDM will be updating the sensor state with dump progress state. The remote terminus will be using polling mechanism on getStateSensorReadings command for dump status update.

Tested: Used pldmtool to set numeric effecter for triggering dump.

2024-08-14 10:32 UTC, riyadixitagra commented
First set of review done here - 
https://github.com/ibm-openbmc/pldm/pull/587

2024-08-14 13:05 UTC, manojkiraneda requested changes

2024-08-14 13:05 UTC, manojkiraneda commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +                                     uint8_t(DimmDumpState::UNAVAILABLE));
was the previous state really unavailable ? what happens if the retry operation worked ?

2024-08-20 12:15 UTC, riyadixitagra commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +
I shouldn't declare tid variable and simply just use TERMINUS_ID ?

2024-08-20 12:15 UTC, riyadixitagra commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +                if (entityType == PLDM_ENTITY_MEMORY_MODULE)
yes we do for PROC

2024-08-20 12:15 UTC, riyadixitagra commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +                                           newDimmContainerID);
Post PDR exchange dimm effecter container ID is changed, hence I am updating the dimm sensor too with that container ID ( so as to have dimm effecters and sensors to have same entity instance and containerID) . But I haven't used it in the logic anywhere, I can remove or we can keep if it is not much overhead ?

2024-08-27 08:28 UTC, manojkiraneda commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +
just directly use TERMINUS_ID

2024-08-27 09:52 UTC, riyadixitagra commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +        dumpStatusMap[entityInstance] = 2;
Mentioning for future work - 
Discussed and required resolution is not present on dbus in 1060. Will have to handle this differently in 1110 as it is supported to read dump object path based on failing unitID

2024-08-27 09:52 UTC, riyadixitagra commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +        dumpStatusMap[entityInstance] = 2;
For 1060 we will continue this way only.

2024-08-27 15:27 UTC, manojkiraneda commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +    std::vector<uint16_t> dimm_info;
```
std::vector<uint16_t> dimm_info;
dimm_info = generateDimmIds();
```

replace it with 

```
auto dimm_info = generateDimmIds();
```

2024-08-28 19:36 UTC, riyadixitagra commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +    for (auto& pdr : pdrs)
I am using reinterpret_cast so can't do it if I use const.

2024-08-28 19:37 UTC, riyadixitagra commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +                                           newDimmContainerID);
I removed it.

2024-08-30 10:47 UTC, manojkiraneda commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +    for (auto& pdr : pdrs)
ack

2024-08-30 10:48 UTC, manojkiraneda approved these changes

2024-08-30 11:26 UTC, Pavithrab7 approved these changes

2024-09-02 07:30 UTC, Pavithrab7 requested changes

2024-09-02 07:30 UTC, Pavithrab7 commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +    static constexpr auto interface = "Dimm";
this looks wrong

2024-09-03 10:30 UTC, Pavithrab7 approved these changes

2024-10-08 12:36 UTC, manojkiraneda approved these changes

2024-10-08 13:06 UTC, Pavithrab7 approved these changes

2024-10-08 21:38 UTC, merged