oem-ibm: Implement SBE dump support
ibm-openbmc/pldm pull request #596
Opened 2024-08-14 11:08 UTC by riyadixitagra

This commit adds support for building Platform Dump Records (PDRs) related to DIMM and PROC entities. It handles DBus method calls for the respective dump types associated with each entity type. Additionally, it monitors dump progress status and triggers a request to set the host effecter.

Test- Used pldmtool platform command for setNumericEffecter.

2024-09-02 08:57 UTC, jaypadath requested changes

2024-09-02 08:57 UTC, jaypadath commented on host-bmc/host_pdr_handler.cpp
> +    if (oemPlatformHandler != nullptr)
Just use if(oemPlatformHandler)

2024-09-02 08:57 UTC, jaypadath commented on libpldmresponder/oem_handler.hpp
> +     *
Add parameter description for entityInstance

2024-09-02 08:57 UTC, jaypadath commented on libpldmresponder/platform.cpp
> +        oemPlatformHandler != nullptr)
Just use oemPlatformHandler instead of oemPlatformHandler != nullptr

2024-09-02 08:57 UTC, jaypadath commented on libpldmresponder/platform.cpp
> +        assert(pdr != NULL);
Just use pdr here

2024-09-02 08:57 UTC, jaypadath commented on oem/ibm/libpldmresponder/oem_ibm_handler.hpp
> +     *
Add entityType @param

2024-09-02 08:57 UTC, jaypadath commented on oem/ibm/libpldmresponder/oem_ibm_handler.hpp
> +    std::unique_ptr<sdbusplus::bus::match::match> sbeDumpMatch;
Replace "match::match" with "match_t"

2024-09-02 08:57 UTC, jaypadath commented on oem/ibm/libpldmresponder/oem_ibm_handler.hpp
> +    // dbus_api::Requester& requester;
Why this is commented. Pls remove unused code.

2024-09-02 08:57 UTC, jaypadath commented on oem/ibm/libpldmresponder/oem_ibm_handler.hpp
> +    HostEffecterDimmMap instanceDimmMap;
Put @brief description

2024-09-03 06:59 UTC, ArchanaKakani commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +        static constexpr auto failingUintIdParam =
typo failingUintIdParam?

2024-09-03 06:59 UTC, ArchanaKakani commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +        auto response = bus.call(method);
Do we need to add timeout value here ? or blocking for 25s is fine?

2024-09-03 06:59 UTC, ArchanaKakani commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +            << e.what() << "\n";
use lg2

2024-09-03 06:59 UTC, ArchanaKakani commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +    for (const auto& [objPath, serviceMap] : response)
GetSubtreePaths will return array of object paths.  Check https://github.com/openbmc/docs/blob/master/architecture/object-mapper.md

2024-09-03 06:59 UTC, ArchanaKakani commented on oem/ibm/libpldmresponder/oem_ibm_handler.hpp
> +    int oemSetNumericEffecterValueHandler(
Doxygen Comment

2024-09-03 06:59 UTC, ArchanaKakani commented on pldmd/dbus_impl_requester.hpp
> +#include <iostream>
This can be removed

2024-09-03 10:22 UTC, riyadixitagra commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +            auto dcmId = id - 48;
Nothing magic it is the position in the string from which ids are being picked - dcm0/cpu1

2024-09-03 10:24 UTC, riyadixitagra commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +        pdr->container_id = 3;
This 3 is mistake it should be 0, will correct( i missed it out). Additionally once we receive PDRs from host we are updating the container ID in function updateContainerID it is in same file.

2024-09-09 09:55 UTC, jaypadath requested changes

2024-09-09 09:55 UTC, jaypadath commented on libpldmresponder/platform.cpp
> +        std::cerr << "Failed to get record by PDR type\n";
Change this to LG2 style

2024-09-09 09:55 UTC, jaypadath commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +    sbeDumpMatch = std::make_unique<sdbusplus::bus::match::match>(
Replace match::match with match_t

2024-09-09 09:55 UTC, jaypadath commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +            "ERR", e.what());
Change e.what() to e

2024-09-16 15:54 UTC, ArchanaKakani commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +                    pldm::utils::reportError(
Could you please elaborate on what problem will it cause if we combine the check as (rc || completionCode)?

2024-09-17 07:52 UTC, riyadixitagra commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +            auto dcmId = id - 48;
As discussed it is planned for dump improvements work

2024-09-17 07:54 UTC, riyadixitagra commented on oem/ibm/libpldmresponder/oem_ibm_handler.cpp
> +                if (rc)
Will take it up in dump improvements.

2024-09-17 08:07 UTC, ArchanaKakani approved these changes

2024-09-17 09:39 UTC, jaypadath approved these changes

2024-09-17 10:24 UTC, ArchanaKakani approved these changes

2024-09-17 13:58 UTC, merged