codeupdate: Fix to boot always from temp side.
ibm-openbmc/pldm pull request #619
Opened 2024-10-07 12:59 UTC by ArchanaKakani

Added missed code and traces from 1060 in code update path.

The problem faced during existing code update code is the delay in receiving the system type. PLDM was setting the fw_boot_side and fw_boot_side_current before building the bios table. So those values where not getting set.
To fix the issue saving the pending bios attributes before setting biostable and resetting it after biostable update.

With the Fix pldm is booting from Temp side after codeupdate.

2024-10-07 14:22 UTC, Pavithrab7 requested changes

2024-10-07 14:22 UTC, Pavithrab7 commented on host-bmc/host_pdr_handler.cpp
> +                if (oemPlatformHandler != nullptr)
if(oemPlatformHandler)

2024-10-07 14:22 UTC, Pavithrab7 commented on host-bmc/host_pdr_handler.cpp
> +                    oemPlatformHandler->startStopTimer(false);
i guess this is already added in oem/ibm/oem_ibm_handler.hpp file?

2024-10-07 14:22 UTC, Pavithrab7 commented on host-bmc/host_pdr_handler.cpp
> +                static constexpr auto searchpath =
this is not needed Archana, powerState mapping  I have added in oem/ibm.

2024-10-07 14:22 UTC, Pavithrab7 commented on oem/ibm/libpldmresponder/platform_oem_ibm.cpp
> +        std::cout <<"platformEventMessage   " << tempStream.str() << std::endl;
do we want to improve this trace by adding function name?

2024-10-08 11:11 UTC, manojkiraneda approved these changes

2024-10-08 11:23 UTC, Pavithrab7 approved these changes

2024-10-08 11:38 UTC, jaypadath approved these changes

2024-10-08 18:29 UTC, merged