oem-ibm : PCIE linkreset support
ibm-openbmc/pldm pull request #639
Opened 2024-12-05 11:05 UTC by riyadixitagra

This commit implements the link reset feature. When the link reset property is set to true, a host state effecter is triggered following which the link reset property is set back to false again.

Tested: Using busctl command

2024-12-05 12:18 UTC, Pavithrab7 requested changes

2024-12-05 12:18 UTC, Pavithrab7 commented on host-bmc/dbus/custom_dbus.hpp
> +PHOSPHOR_LOG2_USING;
why was this added?

2024-12-05 12:18 UTC, Pavithrab7 commented on oem/ibm/configurations/fileTable.json
> +    {
why are these added?

2024-12-05 12:18 UTC, Pavithrab7 commented on oem/ibm/libpldmresponder/utils.cpp
> +                            /*error(
why is this commented?

2024-12-09 05:11 UTC, riyadixitagra commented on oem/ibm/configurations/fileTable.json
> +    {
removed

2024-12-09 05:11 UTC, riyadixitagra commented on host-bmc/dbus/custom_dbus.hpp
> +PHOSPHOR_LOG2_USING;
done

2024-12-09 05:12 UTC, riyadixitagra commented on oem/ibm/libpldmresponder/utils.cpp
> +                            /*error(
done

2024-12-10 03:41 UTC, ArchanaKakani requested changes
LinkReset should be added to logical slots also.
https://github.com/ibm-openbmc/pldm/blob/1060/host-bmc/host_pdr_handler.cpp#L1859

2024-12-10 10:23 UTC, Pavithrab7 requested changes

2024-12-10 10:23 UTC, Pavithrab7 commented on host-bmc/dbus/custom_dbus.hpp
> +#include <phosphor-logging/lg2.hpp>
not needed

2024-12-10 10:23 UTC, Pavithrab7 commented on host-bmc/dbus/linkreset.hpp
> +using Itemlink = sdbusplus::server::object::object<
object_t ?

2024-12-10 10:23 UTC, Pavithrab7 commented on host-bmc/dbus/linkreset.hpp
> +    Link(sdbusplus::bus::bus& bus, const std::string& objPath,
bus_t

2024-12-10 10:23 UTC, Pavithrab7 commented on oem/ibm/libpldmresponder/oem_ibm_handler.hpp
> +    std::vector<std::unique_ptr<sdbusplus::bus::match::match>> matches;
match_t

2024-12-10 10:23 UTC, Pavithrab7 commented on oem/ibm/libpldmresponder/utils.cpp
> +    static constexpr auto MAPPER_BUSNAME = "xyz.openbmc_project.ObjectMapper";
can we make the change to reduce the dbus string constants like this - https://gerrit.openbmc.org/c/openbmc/pldm/+/69194 ?

2024-12-10 14:13 UTC, Pavithrab7 approved these changes

2024-12-10 16:35 UTC, ArchanaKakani approved these changes

2024-12-10 19:29 UTC, merged