Spawn a new thread for the PDR Generation
ibm-openbmc/pldm pull request #79
Opened 2021-12-13 14:07 UTC by manojkiraneda

PDR generation process is quite dbus intensive & in the systems
with more dbus latency , it is observed that PLDM is blocked
while doing these dbus calls & as these are blocking calls pldm
is blocked & was not responding to host which untimately led to
the PHYP initiating the BMC reboot.

Although this does not completely fix the issue, as this only
unblocks the pldm daemon just for the PDR generation process,
This is just a temperory fix, the more concrete and future proof
solution is to switch to sdbusplus::asio infrastructure.

Tested By:

1. Power off & power on in loop - PASS
https://sys-openbmc-dev-jenkins.swg-devops.com/job/OpenBMC-Dev/job/test/job/continuous-integration/job/ebmc/job/power_on_off_loop/5/console

Signed-off-by: Manojkiran Eda <manojkiran.eda@gmail.com>

2021-12-13 22:46 UTC, amboar requested changes

2021-12-13 22:46 UTC, amboar commented on libpldmresponder/platform.cpp
> +                     pldmRepoStatus::PLDM_REPO_BUILDING_IN_PROGRESS)
No sorry, this second load invokes a data race. This needs to be

```
else if (expected == pldmRepoStatus::PLDM_REPO_BUILDING_IN_PROGRESS)
```

2021-12-13 22:46 UTC, amboar commented on libpldmresponder/platform.cpp
> +                     pldmRepoStatus::PLDM_REPO_ALREADY_BUILT)
As above this load invokes a data race. It needs to be

```
else if (expected == pldmRepoStatus::PLDM_REPO_ALREADY_BUILT)
```

2021-12-13 22:46 UTC, amboar commented on libpldmresponder/platform.cpp
> +            }
I think you need

```
} else {
    assert("Unreachable");
}
```
or something equivalent to make sure we have complete coverage of the enum.

2021-12-13 22:46 UTC, amboar commented on libpldmresponder/platform.cpp
> +    if (repoCreated == pldmRepoStatus::PLDM_REPO_NOT_BUILT)
You should do

```
if (repoCreated.compare_exchange_strong(expected, pldmRepoStatus::PLDM_REPO_BUILDING_IN_PROGRESS))
{
...
}
```
again here

2021-12-13 22:48 UTC, amboar commented on libpldmresponder/platform.hpp
>      bool pdrCreated;
This must be std::atomic<bool> pdrCreated as it's used concurrently across threads.

2022-04-06 10:36 UTC, manojkiraneda commented
we dont need this PR anymore (and maintainers are not ready to pull this in ) - as the host bumped up the timeouts.

2022-04-06 10:36 UTC, closed without merging